### PR TITLE
Handle YAML frontmatter

### PR DESCRIPTION
**Pull request by firelizzard18**
If the document starts with a block of valid YAML delimited by ---, present it as a YAML code cell.

Additionally, parse the frontmatter and attach it as document metadata, and keep it up to date by tracking document changes.

### CODE REVIEW

**Comment by roblourens** [comment]
Why do you want the yaml frontmatter as document metadata?

**Comment by firelizzard18** [comment]
I am working on a couple of notebook kernels. I don't intend to use them outside of VSCode, and I like the markdown notebook format, so I want to use this extension instead of writing my own format. It would be useful to be able to store metadata, and doing in YAML frontmatter is the most straightforward way to do that.

It's been a while since I was actively working on this, but IIRC, I want to configure whether outputs are saved. Due to the nature of markdown, the most straightforward way to save outputs is as an embedded XML blob. Users who want to use the notebook as a regular markdown document as well may not want such XML blobs. If I can derive metadata from the YAML frontmatter, I can use that to configure features such as saving cell output. One of my kernels aims to provide a friendly way to query databases; a switch enabling saved outputs could be very useful in that case.

**Comment by roblourens** [comment]
Interesting usecase, and if you want to use markdown notebooks for something I'd like to enable that in this extension rather than have other slightly different markdown notebook extensions. But I don't really understand why markdown files would have outputs, or why you would use markdown files to query databases. Wouldn't you rather use a different format for that?

**Comment by firelizzard18** [comment]
> why you would use markdown files to query databases.

I wrote [this kernel](https://gitlab.com/ethan.reesor/vscode-notebooks/querypad), which supports SQL queries. The following is an incomplete example of what the Markdown could look like:

> Connect to a database
> 
> ```go
> notebook.Connect("my-connection", "<type>", "<connection string>")
> ```
>
> Query the database
> 
> ```sql
> SELECT * FROM MyTable
> ```

Here is a screenshot (from the GitLab project):

image

> Wouldn't you rather use a different format for that?

I want to be able to query databases from a VSCode notebook. Given that I want to use notebooks, I don't see a problem with using Markdown notebooks, nor am I aware of a different notebook format that is clearly better.

> I don't really understand why markdown files would have outputs

Scenario: Alice is a developer or someone else who is happy to use VSCode notebooks. Bob is a database engineer, with access to a database. Alice wants a report from the database, but is unfamiliar with SQL and doesn't have access to the database. So Bob creates a notebook, writes and executes a query to generate the report, and sends the notebook to Alice. If the result of the query (the output cell) is stored in the notebook, Alice can view the report without having access to the database.

In general, it would be valuable to be able to retain query results on-disk in the notebook file.

**Comment by roblourens** [comment]
Markdown is markdown, I don't expect to open a markdown file and execute the code in it, or store output data, or notebook-specific metadata in my markdown file. I'd recommend using your own format that is specific to this scenario. It's pretty easy to come up with some arbitrary JSON format which would be owned by a notebook serializer in your extension.

**Comment by firelizzard18** [comment]
> I don't expect to open a markdown file and execute the code in it

I thought the point of a notebook, including a markdown notebook, was to execute code. Do you intend some other purpose for markdown notebooks?

> I'd recommend using your own format that is specific to this scenario. It's pretty easy to come up with some arbitrary JSON format which would be owned by a notebook serializer in your extension.

I want my notebooks to be human-readable in their raw form. I do not consider JSON to be particularly human readable. Unless I come across some more compelling format, if I were to write my own notebook format it would be something markdown-based.

**Comment by roblourens** [comment]
The main point of this extension is to browse and edit .md files as notebooks. This is using a notebook as a display format for a .md file which is a different goal than using a .md file as a storage format for a real notebook. I'm not sure I want to change the meaning of what a markdown file is and pack extra info into it.

I agree that using .md as a storage format for a notebook is possibly quite nice. JSON is a lot easier to parse :). But if you want to read and write the raw file often, markdown makes sense. Right now I'm thinking that it would make sense to have a different extension and maybe a different file extension for that use case though.

**Pull request closed without merging**
